############# English navigation ##############

# main menu
[[main]]
name = "Start"
url = "/"
weight = 1

[[main]]
name = "Our Service"
url = "service/"
weight = 2

[[main]]
name = "Why us?"
url = "why-us/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

#[[main]]
#weight = 4
#name = "Pages"
#hasChildren = true

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "blog/"

# footer menu
[[footer]]
name = "About us"
url = "team/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
